"""Port for agent template persistence."""

from __future__ import annotations

from typing import Protocol

from src.domain.entities.agent_template import AgentTemplate, TeamDefinition


class AgentTemplateRepository(Protocol):
    """Interface for agent template storage."""

    def save(self, template: AgentTemplate) -> None: ...

    def get_by_id(self, template_id: str) -> AgentTemplate | None: ...

    def get_by_name(self, name: str) -> AgentTemplate | None: ...

    def list_by_scope(self, scope: str) -> list[AgentTemplate]: ...

    def list_by_team(self, team_id: str) -> list[AgentTemplate]: ...

    def list_active(self) -> list[AgentTemplate]: ...

    def remove(self, template_id: str) -> bool: ...

    def update_status(self, template_id: str, status: str) -> bool: ...


class TeamRepository(Protocol):
    """Interface for team definition storage."""

    def save(self, team: TeamDefinition) -> None: ...

    def get_by_id(self, team_id: str) -> TeamDefinition | None: ...

    def get_by_name(self, name: str) -> TeamDefinition | None: ...

    def list_all(self) -> list[TeamDefinition]: ...

    def remove(self, team_id: str) -> bool: ...
