from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.domain.entities.message import AgentMessage


@runtime_checkable
class MessageRepository(Protocol):
    def save(self, msg: AgentMessage) -> str: ...
    def get_by_id(self, msg_id: str) -> AgentMessage | None: ...
    def get_messages_for_agent(self, agent_id: str, limit: int) -> list[AgentMessage]: ...
    def get_history(self, agent_id: str, limit: int) -> list[AgentMessage]: ...
    def delete_expired(self) -> int: ...
