"""Workflow commands for CLI."""

from __future__ import annotations

import logging
import uuid
from pathlib import Path

import typer

from src.application.services.orchestration.events import (
    WorkflowExecuteCompleteEvent,
    WorkflowExecuteStartEvent,
    WorkflowOutlineCompleteEvent,
    WorkflowOutlineStartEvent,
    WorkflowShipCompleteEvent,
    WorkflowShipStartEvent,
    WorkflowVerifyCompleteEvent,
    WorkflowVerifyStartEvent,
    WorktreeCreatedEvent,
    WorktreeMergedEvent,
    WorktreeRemovedEvent,
)
from src.application.services.orchestration.hook_service import HookService
from src.application.services.workflow.state import (
    ExecuteState,
    PlanState,
    Task,
    VerifyState,
    WorkflowPhase,
    get_execute_state_path,
    get_plan_state_path,
    get_verify_state_path,
)
from src.infrastructure.persistence.container import (
    get_memory_service,
    get_tmux_orchestrator,
    get_workspace_manager,
)
from src.interfaces.cli.dependencies import get_hook_service as _get_shared_hook_service

logger = logging.getLogger(__name__)


def _get_hook_service() -> HookService:
    """Get HookService from ctx.obj if available (for testability), else use shared singleton."""
    try:
        ctx = typer.get_current_context()
        if isinstance(ctx.obj, dict):
            if "hook_service" not in ctx.obj:
                ctx.obj["hook_service"] = _get_shared_hook_service()
            return ctx.obj["hook_service"]
    except RuntimeError:
        pass
    return _get_shared_hook_service()


def _dispatch_event(event: object, context: str = "") -> None:
    """Dispatch event with error logging, never raises.

    Args:
        event: The event to dispatch.
        context: Context string for logging (e.g., "outline_start").
    """
    try:
        _get_hook_service().dispatch(event)
    except Exception as e:
        logger.debug("Hook dispatch failed [%s]: %s", context, e)


app = typer.Typer(name="workflow", help="Workflow commands: outline, execute, verify, ship")


def _check_plan_exists() -> PlanState:
    plan_path = get_plan_state_path()
    plan = PlanState.load(plan_path)
    if plan is None:
        typer.echo("Error: No plan found. Run 'memory workflow outline' first.", err=True)
        raise typer.Exit(1)
    return plan


def _check_execute_exists() -> ExecuteState:
    exec_path = get_execute_state_path()
    state = ExecuteState.load(exec_path)
    if state is None:
        typer.echo("Error: No execution found. Run 'memory workflow execute' first.", err=True)
        raise typer.Exit(1)
    return state


def _check_verify_exists() -> VerifyState:
    verify_path = get_verify_state_path()
    state = VerifyState.load(verify_path)
    if state is None:
        typer.echo("Error: No verification found. Run 'memory workflow verify' first.", err=True)
        raise typer.Exit(1)
    return state


@app.command("outline")
def outline(
    task_description: str = typer.Argument(..., help="Task description to plan"),
    plan_file: str = typer.Option(".claude/plans/plan.md", "--plan-file", "-p"),
) -> None:
    session_id = f"plan-{uuid.uuid4().hex[:8]}"

    # Dispatch outline start event
    _dispatch_event(
        WorkflowOutlineStartEvent(plan_id=session_id, task_description=task_description),
        context="outline_start",
    )

    plan_state = PlanState(
        session_id=session_id,
        status="outlined",
        phase=WorkflowPhase.OUTLINED,
        plan_file=plan_file,
    )
    plan_path = get_plan_state_path()
    plan_state.save(plan_path)
    plan_dir = Path(plan_file).parent
    plan_dir.mkdir(parents=True, exist_ok=True)
    plan_content = f"""# Plan: {task_description}

## Session: {session_id}

### Tasks
- [ ] {task_description}

---
Generated by fork_agent workflow
"""
    Path(plan_file).write_text(plan_content)
    typer.echo(f"✓ Plan created: {session_id}")
    typer.echo(f"  Plan file: {plan_file}")
    typer.echo("  Next: Run 'memory workflow execute'")

    # Dispatch outline complete event
    _dispatch_event(
        WorkflowOutlineCompleteEvent(plan_id=session_id, plan_file=plan_file),
        context="outline_complete",
    )

    # Save to memory for history
    try:
        memory = get_memory_service()
        memory.save(
            content=f"workflow:outline:{session_id}:{task_description}",
            metadata={"phase": "outline", "plan_id": session_id, "task_description": task_description},
        )
    except Exception as e:
        logger.debug("Failed to save outline to memory: %s", e)

@app.command("execute")
def execute(
    task_id: str | None = typer.Argument(None, help="Specific task ID to execute"),
    parallel: bool = typer.Option(False, "--parallel", help="Run tasks in parallel"),
    model: str = typer.Option("opencode/glm-5-free", "--model", "-m", help="Agent model to use"),
) -> None:
    plan = _check_plan_exists()
    exec_path = get_execute_state_path()
    exec_state = ExecuteState.load(exec_path)
    session_id = f"exec-{uuid.uuid4().hex[:8]}"

    # Dispatch execute start event
    _dispatch_event(
        WorkflowExecuteStartEvent(plan_id=plan.session_id, task_count=len(plan.tasks)),
        context="execute_start",
    )

    if exec_state is None:
        exec_state = ExecuteState(
            session_id=session_id,
            status="executing",
            phase=WorkflowPhase.EXECUTING,
            tasks=plan.tasks,
        )

    # Filter tasks if task_id specified (create new state instead of mutating)
    if task_id:
        filtered_tasks = [t for t in exec_state.tasks if t.id == task_id]
        exec_state = ExecuteState(
            session_id=exec_state.session_id,
            status="executing",
            phase=WorkflowPhase.EXECUTING,
            tasks=filtered_tasks,
        )

    # Spawn tmux sessions for each task
    spawned_sessions: list[str] = []
    updated_tasks: list[Task] = []

    try:
        orchestrator = get_tmux_orchestrator()

        for task in exec_state.tasks:
            # Generate session name from task slug
            session_name = f"fork-{task.slug[:20]}-{uuid.uuid4().hex[:8]}"

            try:
                # Create tmux session
                success = orchestrator.create_session(session_name)
                if success:
                    logger.info("Created tmux session: %s", session_name)
                    spawned_sessions.append(session_name)

                    # Update task with session info
                    updated_task = Task(
                        id=task.id,
                        slug=task.slug,
                        description=task.description,
                        status="executing",
                        branch=task.branch,
                        worktree_path=task.worktree_path,
                        session_name=session_name,
                        agent_pid=task.agent_pid,
                    )
                    updated_tasks.append(updated_task)

                    # Launch agent in the session (if not parallel, do it sequentially)
                    if not parallel:
                        prompt = f"Execute task: {task.description}"
                        orchestrator.launch_agent(session_name, 0, model, prompt)
                else:
                    logger.warning("Failed to create tmux session: %s", session_name)
                    updated_tasks.append(task)
            except Exception as e:
                logger.error("Error spawning session for task %s: %s", task.id, e)
                updated_tasks.append(task)

        # For parallel execution, launch all agents after sessions are created
        if parallel:
            for task in updated_tasks:
                if task.session_name:
                    try:
                        prompt = f"Execute task: {task.description}"
                        orchestrator.launch_agent(task.session_name, 0, model, prompt)
                    except Exception as e:
                        logger.error("Error launching agent for task %s: %s", task.id, e)

    except Exception as e:
        logger.error("Error initializing TmuxOrchestrator: %s", e)
        updated_tasks = list(exec_state.tasks)  # Use original tasks if orchestrator fails

    # Create worktrees for each task (Wave 3 integration)
    try:
        workspace_manager = get_workspace_manager()
        tasks_with_worktrees: list[Task] = []

        for task in updated_tasks:
            try:
                # Generate worktree name from task slug
                worktree_name = f"task-{task.slug[:30]}"

                # Create the workspace/worktree
                workspace = workspace_manager.create_workspace(worktree_name)
                worktree_path = str(workspace.path)

                logger.info("Created worktree: %s at %s", worktree_name, worktree_path)

                # Dispatch worktree created event
                _dispatch_event(
                    WorktreeCreatedEvent(workspace_name=worktree_name, worktree_path=worktree_path),
                    context="worktree_created",
                )

                # Update task with worktree path and branch
                updated_task = Task(
                    id=task.id,
                    slug=task.slug,
                    description=task.description,
                    status=task.status,
                    branch=worktree_name,  # Set branch to worktree name for cleanup
                    worktree_path=worktree_path,
                    session_name=task.session_name,
                    agent_pid=task.agent_pid,
                )
                tasks_with_worktrees.append(updated_task)

            except Exception as e:
                logger.warning("Failed to create worktree for task %s: %s", task.id, e)
                # Continue without worktree if creation fails
                tasks_with_worktrees.append(task)

        updated_tasks = tasks_with_worktrees

    except Exception as e:
        logger.error("Error initializing WorkspaceManager: %s", e)
        # Continue without worktrees if manager fails

    # Update exec_state with spawned sessions
    exec_state = ExecuteState(
        session_id=exec_state.session_id,
        status="executing",
        phase=WorkflowPhase.EXECUTING,
        tasks=updated_tasks,
    )

    exec_state.save(exec_path)
    typer.echo(f"✓ Execution started: {exec_state.session_id}")
    typer.echo(f"  Tasks: {len(exec_state.tasks)}")
    typer.echo(f"  Sessions spawned: {len(spawned_sessions)}")
    if spawned_sessions:
        typer.echo(f"  Tmux sessions: {', '.join(spawned_sessions)}")
    typer.echo("  Next: Run 'memory workflow verify'")

    # Dispatch execute complete event
    _dispatch_event(
        WorkflowExecuteCompleteEvent(plan_id=plan.session_id, tasks_completed=len(exec_state.tasks)),
        context="execute_complete",
    )

    # Save to memory for history
    try:
        memory = get_memory_service()
        memory.save(
            content=f"workflow:execute:{plan.session_id}:started",
            metadata={
                "phase": "execute",
                "plan_id": plan.session_id,
                "task_count": len(exec_state.tasks),
                "sessions_spawned": len(spawned_sessions),
            },
        )
    except Exception as e:
        logger.debug("Failed to save execute to memory: %s", e)


@app.command("verify")
def verify(
    run_tests: bool = typer.Option(True, "--tests/--no-tests", help="Run tests"),
) -> None:
    plan = _check_plan_exists()
    _check_execute_exists()
    session_id = f"verify-{uuid.uuid4().hex[:8]}"

    # Dispatch verify start event
    _dispatch_event(
        WorkflowVerifyStartEvent(plan_id=plan.session_id, run_tests=run_tests),
        context="verify_start",
    )

    verify_path = get_verify_state_path()
    test_results: dict[str, bool] = {"passed": True} if run_tests else {}
    verify_state = VerifyState(
        session_id=session_id,
        status="verified",
        phase=WorkflowPhase.VERIFIED,
        unlock_ship=True,
        test_results=test_results,
    )
    verify_state.save(verify_path)
    typer.echo(f"✓ Verification complete: {verify_state.session_id}")
    typer.echo(f"  Unlock ship: {verify_state.unlock_ship}")
    typer.echo("  Next: Run 'memory workflow ship'")

    # Dispatch verify complete event
    _dispatch_event(
        WorkflowVerifyCompleteEvent(plan_id=verify_state.session_id),
        context="verify_complete",
    )

    # Save to memory for history
    try:
        memory = get_memory_service()
        memory.save(
            content=f"workflow:verify:{verify_state.session_id}:complete",
            metadata={
                "phase": "verify",
                "plan_id": verify_state.session_id,
                "test_results": verify_state.test_results,
            },
        )
    except Exception as e:
        logger.debug("Failed to save verify to memory: %s", e)


@app.command("ship")
def ship(
    target_branch: str = typer.Option("main", "--branch", "-b", help="Target branch"),
    cleanup: bool = typer.Option(True, "--cleanup/--no-cleanup", help="Cleanup worktrees"),
) -> None:
    verify_state = _check_verify_exists()
    if not verify_state.unlock_ship:
        typer.echo(
            "Error: Verification not complete. Run 'memory workflow verify' first.", err=True
        )
        raise typer.Exit(1)

    # Note: plan check not needed here, verify already validated the workflow

    # Dispatch ship start event
    _dispatch_event(
        WorkflowShipStartEvent(plan_id=verify_state.session_id, target_branch=target_branch),
        context="ship_start",
    )

    exec_path = get_execute_state_path()
    exec_state = ExecuteState.load(exec_path)

    # Cleanup worktrees if requested
    if cleanup and exec_state:
        try:
            workspace_manager = get_workspace_manager()
            cleaned_worktrees: list[str] = []

            for task in exec_state.tasks:
                if task.worktree_path:
                    try:
                        # Extract workspace name from worktree_path or branch
                        worktree_name = task.branch or f"task-{task.slug[:30]}"

                        # Try to merge first
                        try:
                            workspace_manager.merge_workspace(worktree_name, delete_branch=False)
                            logger.info("Merged worktree: %s", worktree_name)

                            # Dispatch merge event
                            _dispatch_event(
                                WorktreeMergedEvent(
                                    workspace_name=worktree_name,
                                    target_branch=target_branch,
                                ),
                                context="worktree_merged",
                            )
                        except Exception as e:
                            logger.warning("Failed to merge worktree %s: %s", worktree_name, e)

                        # Remove the worktree
                        try:
                            workspace_manager.remove_workspace(worktree_name, force=True)
                            logger.info("Removed worktree: %s", worktree_name)
                            cleaned_worktrees.append(worktree_name)

                            # Dispatch remove event
                            _dispatch_event(
                                WorktreeRemovedEvent(workspace_name=worktree_name),
                                context="worktree_removed",
                            )
                        except Exception as e:
                            logger.warning("Failed to remove worktree %s: %s", worktree_name, e)

                    except Exception as e:
                        logger.error("Error cleaning up worktree for task %s: %s", task.id, e)

            if cleaned_worktrees:
                typer.echo(f"  Cleaned up worktrees: {', '.join(cleaned_worktrees)}")

        except Exception as e:
            logger.error("Error initializing WorkspaceManager for cleanup: %s", e)

    typer.echo(f"\u2713 Shipping to {target_branch}")
    typer.echo(f"  Session: {verify_state.session_id}")
    typer.echo("Workflow complete!")

    # Dispatch ship complete event
    _dispatch_event(
        WorkflowShipCompleteEvent(plan_id=verify_state.session_id, target_branch=target_branch),
        context="ship_complete",
    )

    # Save to memory for history
    try:
        memory = get_memory_service()
        memory.save(
            content=f"workflow:ship:{verify_state.session_id}:complete",
            metadata={
                "phase": "ship",
                "plan_id": verify_state.session_id,
                "target_branch": target_branch,
            },
        )
    except Exception as e:
        logger.debug("Failed to save ship to memory: %s", e)


@app.command("status")
def status() -> None:
    plan_path = get_plan_state_path()
    exec_path = get_execute_state_path()
    verify_path = get_verify_state_path()
    plan = PlanState.load(plan_path)
    exec_state = ExecuteState.load(exec_path)
    verify_state = VerifyState.load(verify_path)
    typer.echo("=== Workflow Status ===")
    if plan:
        typer.echo(f"Plan: {plan.phase.value} ({plan.session_id})")
    else:
        typer.echo("Plan: None")
    if exec_state:
        typer.echo(f"Execute: {exec_state.phase.value} ({exec_state.session_id})")
    else:
        typer.echo("Execute: None")
    if verify_state:
        typer.echo(f"Verify: {verify_state.phase.value} ({verify_state.session_id})")
        typer.echo(f"  Unlock ship: {verify_state.unlock_ship}")
    else:
        typer.echo("Verify: None")
