"""Workflow commands for CLI."""

from __future__ import annotations

import logging
import uuid
from pathlib import Path

import typer

from src.application.services.orchestration.events import (
    WorkflowExecuteCompleteEvent,
    WorkflowExecuteStartEvent,
    WorkflowOutlineCompleteEvent,
    WorkflowOutlineStartEvent,
    WorkflowShipCompleteEvent,
    WorkflowShipStartEvent,
    WorkflowVerifyCompleteEvent,
    WorkflowVerifyStartEvent,
)
from src.application.services.orchestration.hook_service import HookService
from src.interfaces.cli.dependencies import get_hook_service as _get_shared_hook_service
from src.application.services.workflow.state import (
    ExecuteState,
    PlanState,
    VerifyState,
    WorkflowPhase,
    get_execute_state_path,
    get_plan_state_path,
    get_verify_state_path,
)

logger = logging.getLogger(__name__)


def _get_hook_service() -> HookService:
    """Get HookService from ctx.obj if available (for testability), else use shared singleton."""
    try:
        ctx = typer.get_current_context()
        if isinstance(ctx.obj, dict):
            if "hook_service" not in ctx.obj:
                ctx.obj["hook_service"] = _get_shared_hook_service()
            return ctx.obj["hook_service"]
    except RuntimeError:
        pass
    return _get_shared_hook_service()


def _dispatch_event(event: object, context: str = "") -> None:
    """Dispatch event with error logging, never raises.

    Args:
        event: The event to dispatch.
        context: Context string for logging (e.g., "outline_start").
    """
    try:
        _get_hook_service().dispatch(event)
    except Exception as e:
        logger.debug("Hook dispatch failed [%s]: %s", context, e)


app = typer.Typer(name="workflow", help="Workflow commands: outline, execute, verify, ship")


def _check_plan_exists() -> PlanState:
    plan_path = get_plan_state_path()
    plan = PlanState.load(plan_path)
    if plan is None:
        typer.echo("Error: No plan found. Run 'memory workflow outline' first.", err=True)
        raise typer.Exit(1)
    return plan


def _check_execute_exists() -> ExecuteState:
    exec_path = get_execute_state_path()
    state = ExecuteState.load(exec_path)
    if state is None:
        typer.echo("Error: No execution found. Run 'memory workflow execute' first.", err=True)
        raise typer.Exit(1)
    return state


def _check_verify_exists() -> VerifyState:
    verify_path = get_verify_state_path()
    state = VerifyState.load(verify_path)
    if state is None:
        typer.echo("Error: No verification found. Run 'memory workflow verify' first.", err=True)
        raise typer.Exit(1)
    return state


@app.command("outline")
def outline(
    task_description: str = typer.Argument(..., help="Task description to plan"),
    plan_file: str = typer.Option(".claude/plans/plan.md", "--plan-file", "-p"),
) -> None:
    session_id = f"plan-{uuid.uuid4().hex[:8]}"

    # Dispatch outline start event
    _dispatch_event(
        WorkflowOutlineStartEvent(plan_id=session_id, task_description=task_description),
        context="outline_start",
    )

    plan_state = PlanState(
        session_id=session_id,
        status="outlined",
        phase=WorkflowPhase.OUTLINED,
        plan_file=plan_file,
    )
    plan_path = get_plan_state_path()
    plan_state.save(plan_path)
    plan_dir = Path(plan_file).parent
    plan_dir.mkdir(parents=True, exist_ok=True)
    plan_content = f"""# Plan: {task_description}

## Session: {session_id}

### Tasks
- [ ] {task_description}

---
Generated by fork_agent workflow
"""
    Path(plan_file).write_text(plan_content)
    typer.echo(f"✓ Plan created: {session_id}")
    typer.echo(f"  Plan file: {plan_file}")
    typer.echo("  Next: Run 'memory workflow execute'")

    # Dispatch outline complete event
    _dispatch_event(
        WorkflowOutlineCompleteEvent(plan_id=session_id, plan_file=plan_file),
        context="outline_complete",
    )


@app.command("execute")
def execute(
    task_id: str | None = typer.Argument(None, help="Specific task ID to execute"),
    parallel: bool = typer.Option(False, "--parallel", help="Run tasks in parallel"),  # noqa: ARG001
) -> None:
    plan = _check_plan_exists()
    exec_path = get_execute_state_path()
    exec_state = ExecuteState.load(exec_path)
    session_id = f"exec-{uuid.uuid4().hex[:8]}"

    # Dispatch execute start event
    _dispatch_event(
        WorkflowExecuteStartEvent(plan_id=plan.session_id, task_count=len(plan.tasks)),
        context="execute_start",
    )

    if exec_state is None:
        exec_state = ExecuteState(
            session_id=session_id,
            status="executing",
            phase=WorkflowPhase.EXECUTING,
            tasks=plan.tasks,
        )

    # Filter tasks if task_id specified (create new state instead of mutating)
    if task_id:
        filtered_tasks = [t for t in exec_state.tasks if t.id == task_id]
        exec_state = ExecuteState(
            session_id=exec_state.session_id,
            status="executing",
            phase=WorkflowPhase.EXECUTING,
            tasks=filtered_tasks,
        )

    exec_state.save(exec_path)
    typer.echo(f"✓ Execution started: {exec_state.session_id}")
    typer.echo(f"  Tasks: {len(exec_state.tasks)}")
    typer.echo("  Next: Run 'memory workflow verify'")

    # Dispatch execute complete event
    _dispatch_event(
        WorkflowExecuteCompleteEvent(plan_id=plan.session_id, tasks_completed=len(exec_state.tasks)),
        context="execute_complete",
    )


@app.command("verify")
def verify(
    run_tests: bool = typer.Option(True, "--tests/--no-tests", help="Run tests"),
) -> None:
    plan = _check_plan_exists()
    _check_execute_exists()
    session_id = f"verify-{uuid.uuid4().hex[:8]}"

    # Dispatch verify start event
    _dispatch_event(
        WorkflowVerifyStartEvent(plan_id=plan.session_id, run_tests=run_tests),
        context="verify_start",
    )

    verify_path = get_verify_state_path()
    test_results: dict[str, bool] = {"passed": True} if run_tests else {}
    verify_state = VerifyState(
        session_id=session_id,
        status="verified",
        phase=WorkflowPhase.VERIFIED,
        unlock_ship=True,
        test_results=test_results,
    )
    verify_state.save(verify_path)
    typer.echo(f"✓ Verification complete: {verify_state.session_id}")
    typer.echo(f"  Unlock ship: {verify_state.unlock_ship}")
    typer.echo("  Next: Run 'memory workflow ship'")

    # Dispatch verify complete event
    _dispatch_event(
        WorkflowVerifyCompleteEvent(plan_id=plan.session_id, test_results=test_results),
        context="verify_complete",
    )


@app.command("ship")
def ship(
    target_branch: str = typer.Option("main", "--branch", "-b", help="Target branch"),
    cleanup: bool = typer.Option(True, "--cleanup/--no-cleanup", help="Cleanup worktrees"),  # noqa: ARG001
) -> None:
    verify_state = _check_verify_exists()
    if not verify_state.unlock_ship:
        typer.echo(
            "Error: Verification not complete. Run 'memory workflow verify' first.", err=True
        )
        raise typer.Exit(1)

    # Dispatch ship start event
    _dispatch_event(
        WorkflowShipStartEvent(plan_id=verify_state.session_id, target_branch=target_branch),
        context="ship_start",
    )

    typer.echo(f"✓ Shipping to {target_branch}")
    typer.echo(f"  Session: {verify_state.session_id}")
    typer.echo("Workflow complete!")

    # Dispatch ship complete event
    _dispatch_event(
        WorkflowShipCompleteEvent(plan_id=verify_state.session_id, target_branch=target_branch),
        context="ship_complete",
    )


@app.command("status")
def status() -> None:
    plan_path = get_plan_state_path()
    exec_path = get_execute_state_path()
    verify_path = get_verify_state_path()
    plan = PlanState.load(plan_path)
    exec_state = ExecuteState.load(exec_path)
    verify_state = VerifyState.load(verify_path)
    typer.echo("=== Workflow Status ===")
    if plan:
        typer.echo(f"Plan: {plan.phase.value} ({plan.session_id})")
    else:
        typer.echo("Plan: None")
    if exec_state:
        typer.echo(f"Execute: {exec_state.phase.value} ({exec_state.session_id})")
    else:
        typer.echo("Execute: None")
    if verify_state:
        typer.echo(f"Verify: {verify_state.phase.value} ({verify_state.session_id})")
        typer.echo(f"  Unlock ship: {verify_state.unlock_ship}")
    else:
        typer.echo("Verify: None")
