"""Workflow commands for CLI."""

from __future__ import annotations

import uuid
from pathlib import Path

import typer

from src.application.services.workflow.state import (
    ExecuteState,
    PlanState,
    VerifyState,
    WorkflowPhase,
    get_execute_state_path,
    get_plan_state_path,
    get_verify_state_path,
)

app = typer.Typer(name="workflow", help="Workflow commands: outline, execute, verify, ship")


def _check_plan_exists() -> PlanState:
    plan_path = get_plan_state_path()
    plan = PlanState.load(plan_path)
    if plan is None:
        typer.echo("Error: No plan found. Run 'memory workflow outline' first.", err=True)
        raise typer.Exit(1)
    return plan


def _check_execute_exists() -> ExecuteState:
    exec_path = get_execute_state_path()
    state = ExecuteState.load(exec_path)
    if state is None:
        typer.echo("Error: No execution found. Run 'memory workflow execute' first.", err=True)
        raise typer.Exit(1)
    return state


def _check_verify_exists() -> VerifyState:
    verify_path = get_verify_state_path()
    state = VerifyState.load(verify_path)
    if state is None:
        typer.echo("Error: No verification found. Run 'memory workflow verify' first.", err=True)
        raise typer.Exit(1)
    return state


@app.command("outline")
def outline(
    task_description: str = typer.Argument(..., help="Task description to plan"),
    plan_file: str = typer.Option(".claude/plans/plan.md", "--plan-file", "-p"),
) -> None:
    session_id = f"plan-{uuid.uuid4().hex[:8]}"
    plan_state = PlanState(
        session_id=session_id,
        status="outlined",
        phase=WorkflowPhase.OUTLINED,
        plan_file=plan_file,
    )
    plan_path = get_plan_state_path()
    plan_state.save(plan_path)
    plan_dir = Path(plan_file).parent
    plan_dir.mkdir(parents=True, exist_ok=True)
    plan_content = f"""# Plan: {task_description}

## Session: {session_id}

### Tasks
- [ ] {task_description}

---
Generated by fork_agent workflow
"""
    Path(plan_file).write_text(plan_content)
    typer.echo(f"✓ Plan created: {session_id}")
    typer.echo(f"  Plan file: {plan_file}")
    typer.echo("  Next: Run 'memory workflow execute'")


@app.command("execute")
def execute(
    task_id: str | None = typer.Argument(None, help="Specific task ID to execute"),
    parallel: bool = typer.Option(False, "--parallel", help="Run tasks in parallel"),  # noqa: ARG001
) -> None:
    plan = _check_plan_exists()
    exec_path = get_execute_state_path()
    exec_state = ExecuteState.load(exec_path)
    if exec_state is None:
        exec_state = ExecuteState(
            session_id=f"exec-{uuid.uuid4().hex[:8]}",
            status="executing",
            phase=WorkflowPhase.EXECUTING,
            tasks=plan.tasks,
        )
    if task_id:
        exec_state.tasks = [t for t in exec_state.tasks if t.id == task_id]
    exec_state.status = "executing"
    exec_state.phase = WorkflowPhase.EXECUTING
    exec_state.save(exec_path)
    typer.echo(f"✓ Execution started: {exec_state.session_id}")
    typer.echo(f"  Tasks: {len(exec_state.tasks)}")
    typer.echo("  Next: Run 'memory workflow verify'")


@app.command("verify")
def verify(
    run_tests: bool = typer.Option(True, "--tests/--no-tests", help="Run tests"),
) -> None:
    _check_plan_exists()
    _check_execute_exists()
    verify_path = get_verify_state_path()
    verify_state = VerifyState(
        session_id=f"verify-{uuid.uuid4().hex[:8]}",
        status="verified",
        phase=WorkflowPhase.VERIFIED,
        unlock_ship=True,
    )
    if run_tests:
        verify_state.test_results = {"passed": True}
    verify_state.save(verify_path)
    typer.echo(f"✓ Verification complete: {verify_state.session_id}")
    typer.echo(f"  Unlock ship: {verify_state.unlock_ship}")
    typer.echo("  Next: Run 'memory workflow ship'")


@app.command("ship")
def ship(
    target_branch: str = typer.Option("main", "--branch", "-b", help="Target branch"),
    cleanup: bool = typer.Option(True, "--cleanup/--no-cleanup", help="Cleanup worktrees"),  # noqa: ARG001
) -> None:
    verify_state = _check_verify_exists()
    if not verify_state.unlock_ship:
        typer.echo(
            "Error: Verification not complete. Run 'memory workflow verify' first.", err=True
        )
        raise typer.Exit(1)
    typer.echo(f"✓ Shipping to {target_branch}")
    typer.echo(f"  Session: {verify_state.session_id}")
    typer.echo("Workflow complete!")


@app.command("status")
def status() -> None:
    plan_path = get_plan_state_path()
    exec_path = get_execute_state_path()
    verify_path = get_verify_state_path()
    plan = PlanState.load(plan_path)
    exec_state = ExecuteState.load(exec_path)
    verify_state = VerifyState.load(verify_path)
    typer.echo("=== Workflow Status ===")
    if plan:
        typer.echo(f"Plan: {plan.phase.value} ({plan.session_id})")
    else:
        typer.echo("Plan: None")
    if exec_state:
        typer.echo(f"Execute: {exec_state.phase.value} ({exec_state.session_id})")
    else:
        typer.echo("Execute: None")
    if verify_state:
        typer.echo(f"Verify: {verify_state.phase.value} ({verify_state.session_id})")
        typer.echo(f"  Unlock ship: {verify_state.unlock_ship}")
    else:
        typer.echo("Verify: None")
